server:
  port: 8080
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    initialization-mode: NEVER #自动执行sql脚本初始化数据库，可选值:ALWAYS|EMBEDDED|NEVER
    schema: classpath:db/schema-source.sql,classpath:db/schema-target.sql
    data: classpath:db/data-source.sql,classpath:db/data-target.sql
    db1:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/dynamic-source?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      db-type: mysql
      validation-query: "select 1"
      max-active: 16
      min-idle: 4
    db2:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://localhost:3306/dynamic-target?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      db-type: mysql
      validation-query: "select 1"
    druid:
      filter:
        stat:
          enabled: true  #是否激活sql监控
        wall:
          enabled: true  #是否激活sql防火墙
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"   #浏览器访问localhost:8080/druid，进入监控界面
        login-username: admin
        login-password: admin@123
mybatis-plus:
  auto-generator: true


